config/routes.rb
Ceping::Application.routes.draw do

  captcha_route
  root :to => 'main#login'

  match '/login' => 'main#login', :via => :get
  match '/logout' => 'main#logout', :via => :get
  match '/signup' => 'main#signup', :via => :get

  resources :main do
    collection do
      post 'user_create'
      post 'login_check'
      get 'check_login'
    end
  end

end

app/models/member.rb
#encoding:UTF-8
class Member < ActiveRecord::Base
  has_many :babies
  validates :user, :presence => {:message => "用户名不能为空"},
            :uniqueness => {:message => "用户名以存在！"},
            :length => {:minimum => 6, :maximum => 20, :message => "用户名长度应在6至20个字符之间"}
  validates :password, :presence => {:message => "密码不能为空"},
            :length => {:minimum => 6, :maximum => 254, :message => "密码至少6个字符"}
  validates :realname, :presence => {:message => "真实姓名不能为空"},
            :length => {:minimum => 2, :maximum => 10, :message => "请填写真实姓名"}
  validates :tel, :presence => {:message => "请填写真实手机号码！"}
  validates_format_of :tel, :multiline => true, :message => "手机号码不正确!", :with => /^(13[0-9]|15[0-9]|18[0-9])\d{8}$/

  # 密码加密
  def self.encrypt_password(password)
    Digest::MD5.hexdigest(password)
  end

  # 验证用户登录参数
  def self.valid_use_login_params(login_name, password)
    if (login_name.blank? || password.blank?)
    else
      return true
    end
  end

  # 验证登录
  def self.login_check(user, password)
    encrypt_password = Member.encrypt_password(password)
    return Member.where(:user => user, :password => encrypt_password).first
  end

  # 检查登录名是否存在
  def self.check_login_exist(user)
    accounts = Member.where(:user => user)
    accounts.blank? ? false : true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # reset captcha code after each request for security
  after_filter :reset_last_captcha_code!

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :prepare_member, :except => [:logout]
  before_filter :login_filter, :except => [:login, :login_check, :signup, :user_create, :check_login, :logout]
  before_filter :logined_filter, :only => [:quizs]

  # 登录
  def prepare_member
    if session[:member_id]
      @member_curr = Member.find_by_id(session[:member_id])
      unless @member_curr
        session[:member_id] = nil
        redirect_to login_path and return
      end
    end
  end

  # 未登录过滤
  def login_filter
    if !@member_curr
      redirect_to login_path and return
    end
  end

  # 已登录过滤
  def logined_filter
    if @member_curr
      redirect_to root_path and return
    end
  end
end

app/controllers/main_controller.rb
#encoding=UTF-8
class MainController < ApplicationController
  protect_from_forgery :except => :login_check
  #  before_filter :login_filter,:only => [:login, :login_check, :signup, :user_create]

  # 登录页
  def login;
  end

  # 登录验证
  #
  # 2: 参数错误
  # 0: 成功
  # 1：失败
  def login_check
    login_name = params[:name]
    password = params[:password]
    flag = nil
    if Member.valid_use_login_params(login_name, password)
      member = Member.login_check(login_name, password)
      if member.blank?
        # 登录失败
        flag = 1
      else
        do_login(member)
        flag = 0
      end
    else
      # 参数非法
      flag = 0
    end
    respond_to do |format|
      format.html do
        redirect_to root_path and return
      end
      format.json { render :json => {:success => flag} }
    end
  end

  # 注册页
  def signup
    @member = Member.new
  end

  # 用户注册提交
  def user_create
    user = params[:member][:user]
    password = params[:member][:password]
    passagain = params[:member][:member_passagain]
    realname = params[:member][:realname]
    tel = params[:member][:tel]
    address = params[:member][:address]
    @member = Member.new(:user => user,
                         :password => Member.encrypt_password(password),
                         :realname => realname,
                         :tel => tel,
                         :address => address
    )
    if @member.save
      #成功
      member = Member.login_check(user, password)
      respond_to do |format|
        format.json do
          if @member
            do_login(member)
            render :json => {:success => 0, :go_url => root_path}
          else
            render :json => {:success => 1}
          end
        end
      end
    else
      redirect_to :back and return
    end
  end

  #验证登录名
  def check_login
    user = params[:member][:user]
    render :text => Member.check_login_exist(user) ? "false" : "true"
  end

  # 首页

  def index
  end

  # 注销
  def logout
    session[:member_id] = nil

    redirect_to "/" and return
  end

  protected

  # 登录
  def do_login(member)
    session[:member_id] = member.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>登陆</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "jquery.validate", "data-turbolinks-track" => true %>
  <script src="/javascripts/jquery-migrate-1.1.1.js" type="text/javascript"></script>
  <link href="/stylesheets/global.css" rel="stylesheet" type="text/css">
  <link href="/stylesheets/clear.css" rel="stylesheet" type="text/css">
  <link href="/stylesheets/child.css" rel="stylesheet" type="text/css">
  <link href="/stylesheets/boxy.css" rel="stylesheet" type="text/css">
  <link href="/stylesheets/cpnew.css" rel="stylesheet" type="text/css">
  <script src="/javascripts/jquery.boxy.cn.js" type="text/javascript"></script>
  <%= csrf_meta_tags %>
  <script>
      <%if flash[:alert]%>
      alert('<%=flash[:alert]%>');
      <%end%>
  </script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/login.html.erb
<% if @member_curr %>
    <div class="quiz_main_box">
      <div id="quiz"><!-- 宝宝测试 -->
        <div id="quiz_signup_head">
          <h2>早教评测:测试可以帮助您更了解您的宝宝，并及时端正宝宝的行为习惯。我们将根据测试结果向您提供准确专业的点评。</h2>
        </div>
        <div id="quiz_signup_body">
          <div class="loginFormBox">
            <p class="quiz_titles" style="background:none; letter-spacing:2px; padding-top:20px">
              尊敬的用户：<%= @member_curr.user %>欢迎您！
              <a href="<%= logout_path %>">[注销]</a></p>
          </div>
        </div>
      </div>
    </div>
<% else %>
    <div class="quiz_main_box">
      <div id="quiz"><!-- 宝宝测试 -->
        <div id="quiz_signup_head">
          <h2>早教评测:测试可以帮助您更了解您的宝宝，并及时端正宝宝的行为习惯。我们将根据测试结果向您提供准确专业的点评。</h2>
        </div>
        <div id="quiz_signup_body">
          <p class="quiz_titles" style="background:none; letter-spacing:2px; padding-top:20px">用户登录 | 新用户请先<a href="/signup">注册</a>后登录</p>
          <div class="loginFormBox">
            <form id="login_form">
              <p>
                <span>用户名：</span>
                <input class="nfyy-big-input" name="name" type="text" />
              </p>
              <p>
                <span>密&nbsp;&nbsp;码：</span>
                <input class="nfyy-big-input" name="password" type="password" />
              </p>
              <p/>
              <input class="nfyy-login-submit" name="commit" type="submit" value="" />
              <p/>
              <script type="text/javascript">
                  $("#login_form").validate({
                      rules: {
                          "name": {
                              required: true
                          },
                          "password": {
                              required: true
                          }
                      },
                      messages: {
                          'name': {
                              required: '用户名不能为空'
                          },
                          "password": {
                              required: '密码不能为空'
                          }
                      },
                      errorPlacement: function(error, element) {
                          error.appendTo(element.parent());
                      },
                      submitHandler: function(form) {  //通过之后回调
                          var param = $("#login_form").serialize();
                          $.ajax({
                              url : "<%= login_check_main_index_path %>",
                              type : "post",
                              dataType : "json",
                              data: param,
                              success : function(data) {
                                  var award = eval (data);
                                  if (award.success == 0){
                                      alert("登录成功");
                                      location.href ="<%=root_path%>"
                                  }
                                  if (award.success == 1){
                                      alert("用户名或密码错误");
                                  }
                              }
                          });
                      }
                  });
              </script>
            </form>
          </div>
        </div>
      </div>
    </div>
<%end%>

app/views/main/signup.html.erb
<script>
    <% if flash[:error_msg]%>
    alert('<%=flash[:error_msg]%>');
    <% end%>
</script>
<div class="quiz_main_box">
  <div id="quiz">
    <div id="quiz_signup_head">
    </div>
    <div id="quiz_signup_body">
      <p class="quiz_titles" style="background-position:66px 13px;">用户注册</p>

      <div class="sinupFormBox">
        <%= form_for(@member, :url => user_create_main_index_path, :method => "post", :html => {:id => "user_signup"}) do |f| %>
            <form id="user_signup">
              <p>
                <span>用&nbsp;户&nbsp;名:</span>
                <input class="big-input" name="member[user]" size="30" type="text"/>
                <label class="error sign_up_info">6-20位字符，可使用字母、数字或符号的组合</label>
              </p>

              <p>
                <span>密&nbsp;&nbsp;&nbsp;&nbsp;码:</span>
                <input class="big-input" id="member_password" name="member[password]" size="30" type="password"/>
                <label class="error sign_up_info">6-20位字符，可使用字母、数字或符号的组合</label>
              </p>

              <p>
                <span>确认密码:</span>
                <input class="big-input" id="member_passagain" name="member_passagain" size="30" type="password"/>
              </p>

              <p>
                <span>真实姓名:</span>
                <input class="big-input" name="member[realname]" size="30" type="text"/>
                <label class="error sign_up_info">支持中文，最多20个字符，中文算2个字符</label>
              </p>

              <p>
                <span>手&nbsp;&nbsp;&nbsp;&nbsp;机:</span>
                <input class="big-input" name="member[tel]" size="30" type="text"/>
                <label class="error sign_up_info">请输入您的手机号码</label>
              </p>

              <p>
                <span>地&nbsp;&nbsp;&nbsp;&nbsp;址:</span>
                <input class="big-input" name="member[address]" size="30" type="text"/>
                <label class="error sign_up_info">请输入您的联系地址</label>
              </p>

              <% if request.post? %>
                      <p><%= valid_captcha?(params[:captcha]) ? 'valid' : 'invalid' %> captcha</p>
              <% end %>
              <p>
                <span>验&nbsp;证&nbsp;码:</span>
                <input class="big-input" name="member[captcha]" size="30" type="text"/>
                <%= captcha_tag %>
              </p>

              <p>
                <strong style="color:#cd210a; font-weight:bold;">特别提示：</strong>为了保证用户安全以及忘记用户名、密码等特殊情况，
                <strong style="color:#cd210a;">请务必正确填写信息。</strong>
              </p>

              <p class="sign-bfld">
                <input class="btn-signup backgroundTrans" id="member_submit" name="commit" type="submit" value=""/>
              </p>
            </form>
        <% end %>
        <script type="text/javascript">
            $(document).ready(function () {
                $.validator.methods.check_username = function (value, element, param) {
                    var reg = /^(13[0-9]|15[0-9]|18[0-9])\d{8}$/i;
                    if (reg.test(value)) {
                        return false;
                    }
                    return true;
                };
                $.validator.methods.mobile = function (value) {
                    var mobile = /^1[3458]\d{9}$/i;
                    return mobile.test(value)
                };

                $("img[alt='captcha']").each(function (index, item) {
                    item.title = '看不清？点击刷新'
                })
                $("img[alt='captcha']").bind("click", function () {
                    this.src = this.src + '?'
                });

                $(function () {
                    $("#user_signup").validate({
                        rules: {
                            "member[user]": {
                                required: true,
                                check_username: true,
                                minlength: 6,
                                remote: "<%=check_login_main_index_path%>"
                            },
                            "member[password]": {
                                required: true,
                                minlength: 6
                            },
                            "member_passagain": {
                                required: true,
                                minlength: 6,
                                equalTo: "#member_password"
                            },
                            "member[realname]": {
                                required: true,
                                minlength: 2,
                                maxlength: 20
                            },
                            "member[tel]": {
                                required: true,
                                mobile: true,
                                rangelength: [11, 11]
                            },
                            "member[address]": {
                                required: true
                            },
                            "member[captcha]": {
                                required: true
                            }
                        },
                        messages: {
                            "member[user]": {
                                required: "6-20位字符，可使用字母、数字或符号的组合",
                                check_username: "登录名不能含特殊字符",
                                minlength: "登录名不能少于6个字符",
                                remote: "用户名已存在"
                            },
                            "member[password]": {
                                required: "6-20位字符，可使用字母、数字或符号的组合",
                                minlength: jQuery.format("密码不能小于6个字符")
                            },
                            "member_passagain": {
                                required: "请输入确认密码",
                                minlength: jQuery.format("不能小于6个字符"),
                                equalTo: "两次输入密码不一致"
                            },
                            "member[realname]": {
                                required: "请输入昵称",
                                minlength: "不能少于2个字符",
                                maxlength: "不能多于20个字符"
                            },
                            "member[tel]": {
                                required: "电话不能为空！",
                                mobile: "手机格式不正确!",
                                rangelength: "请输入正确的手机号码！"
                            },
                            "member[address]": {
                                required: "请输入地址"
                            },
                            "member[captcha]": {
                                required: "请输入验证码"
                            }
                        },
                        errorPlacement: function (error, element) {
                            error.appendTo(element.parent());
                        },
                        submitHandler: function (form) {  //通过之后回调
                            var param = $("#user_signup").serialize();
                            $.ajax({
                                url: "<%= user_create_main_index_path %>",
                                type: 'POST',
                                dataType: "json",
                                data: param,
                                success: function (data) {
                                    var award = eval(data);
                                    if (award.success == 0) {
                                        alert("注册成功");
                                        setInterval(window.location.href = award.go_url, 1000)
                                    }
                                    if (award.success == 1) {
                                        alert("注册用户失败！");
                                    }
                                }
                            });
                        }
                    });
                });
            });
        </script>
      </div>
    </div>
  </div>
</div>